name: ubuntu-bash
services:
  ubuntu:
    image: ubuntu
    container_name: ubuntu
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
      net.ipv6.conf.default.disable_ipv6: 0
    tty: true
    entrypoint: /bin/bash

networks:
  default:
    external: true
    name: local-infra-main-net
